server:
  port: 80
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    #    url: "jdbc:mysql://201.201.201.173:3306/banshee?characterEncoding=utf8"
    #    username:  dev
    #    password:  devMysql!@#!123
    url: "jdbc:mysql://10.0.250.1:3306/unipayDEV?characterEncoding=utf8"
    username:  dev
    password:  ChongQing@MySQL3306
    driver-class-name: "com.mysql.jdbc.Driver"
  redis:
    database: 7
    host: 10.0.250.1
    port: 6379
    timeout: 5s
    jedis:
      pool:
        max-idle: 8
        max-active: 64
  rabbitmq:
    host: 10.0.250.1
    port: 5672
    username: gtsy
    password: gtsy
    virtual-host: vhost
    publisher-confirms: true
    publisher-returns: true
    template:
      default-receive-queue: unipay_order_queen
      exchange: unipay_order_exchange
      routing-key: unipay_order_route
    listener:
      simple:
        acknowledge-mode: MANUAL
      direct:
        acknowledge-mode: MANUAL
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.web: DEBUG
    cn.gotoil.unipay.model.mapper: ERROR
    cn.gotoil: INFO
  path: logs

isDebug: true

#本机域名或者IP 必须能外网访问的
domain: "http://737wwt.natappfree.cc"
#微信授权域名 勇哥那的地址 第一个占位符是wxappid 第二个占位符是跳转的地址
#wechat_open_id_grant_url: "http://thirdparty.guotongshiyou.cn/third_party/oauth/wechat/%s?auth_type=1&app_id=%s&sign=%s&s_time=%s&redirect=%s"
wechat_open_id_grant_url: "http://jumper.dbbank.xyz/third_party/oauth/wechat/%s?auth_type=1&app_id=%s&sign=%s&s_time=%s&redirect=%s"
wechat_open_id_grant_id: "unipay"
wechat_open_id_grant_key: "ljofjdfjdsf324234"


bill:
  defaultAuthenticationType: Signature
  #  defaultAuthenticationType: NONE
  keyOfHashCompareAuthenticationPathPrefix: "/api/v1/"
  apiResponseAroundControllerPackagesExecution: "execution(* cn.gotoil.unipay.controller..*.*Action(..))"
  keyOfHashCompareAuthenticationProviderClass: "cn.gotoil.unipay.classes.HashCompareAuthenticationKeyProvider"
  keyOfHashCompareAuthenticationProviderMethod: "key"
  allowDevSkipSignature: "YES"
  exceptBodyContentHttpServletRequestWrapperUrls:
  - "/web/"
  - "/static/"
secure:
  filterUrl: "/web/**"  ##权限控制的
  billWebAuthenicationClass: "cn.gotoil.unipay.classes.BillWebAuthenticationProvider"
  billWebAuthenicationMethod: "findByUserCode"
  tokenExpirseTimeMinute: 60

